Feat/daily problem
yulecc/lucifer-official-web pull request #18
Opened 2020-03-04 07:42 UTC by jerkjoe

1) style changes 
2) search by keyword 
3) users can now click on the title and redirect to issue page

2020-03-04 10:38 UTC, azl397985856 requested changes
👍 代码质量还是不错的哦

2020-03-04 10:38 UTC, azl397985856 commented on src/views/Everyday.vue
> +              tag.name === 'Daily Question'
不建议三目运算符嵌套

2020-03-04 10:38 UTC, azl397985856 commented on src/views/Everyday.vue
> +      totalPages: 0,
```suggestion
```

2020-03-04 10:38 UTC, azl397985856 commented on src/views/Everyday.vue
> +      totalPages: 0,
无用，建议删除

2020-03-04 10:38 UTC, azl397985856 commented on src/views/Everyday.vue
> +      const url = keyword
这个判断是多余的

2020-03-04 10:38 UTC, azl397985856 commented on src/views/Everyday.vue
> +        data: { items, total_count }
为什么不驼峰，还禁用了eslint呢

2020-03-04 10:38 UTC, azl397985856 commented on src/views/Everyday.vue
> +      // eslint-disable-next-line @typescript-eslint/camelcase
same problem

2020-03-04 10:38 UTC, azl397985856 commented on src/views/Everyday.vue
> +        current ? current : 0,
```suggestion
        current || 0,

```

2020-03-04 10:38 UTC, azl397985856 commented on src/views/Everyday.vue
> +        console.log(item)
```suggestion

```

2020-03-04 10:38 UTC, azl397985856 commented on src/views/Everyday.vue
> +    },
没有处理异常情况。 这会导致如果接口挂了，将一直loading

2020-03-04 10:38 UTC, azl397985856 commented on src/views/Everyday.vue
> +<style>
```suggestion
<style scoped>

```

2020-03-04 10:55 UTC, azl397985856 commented
功能问题：

- 列表没有居中
- 增加“共xxx页”显示
- 不支持tag搜索
- 不支持按照锁定搜索
- 数据源有问题。 搜索应该是【每日一题】， 这样不会将其他无关的查询进来，比如：
![image](https://user-images.githubusercontent.com/12479470/75872723-a6115a00-5e49-11ea-8faf-2add0f6c5bca.png)

2020-03-05 06:52 UTC, jerkjoe commented on src/views/Everyday.vue
> +              tag.name === 'Daily Question'
已改成用method返回。

2020-03-05 10:09 UTC, azl397985856 commented
- 点击tag是搜索这个交互有点奇怪。 用户很难理解，最好是下拉框类型

2020-03-06 04:53 UTC, azl397985856 requested changes

2020-03-06 05:42 UTC, merged