视频区初版
yulecc/lucifer-official-web pull request #31
Opened 2020-03-08 14:26 UTC by ZStar01

视频区第一版代码,开发了获取某些用户在b站的全部作品,以及在线观看,搜索作品等功能

2020-03-08 14:46 UTC, azl397985856 requested changes

2020-03-08 14:46 UTC, azl397985856 commented on public/index.html
> +    <meta name="referrer" content="no-referrer"/>
这里需要增加注释，解释为什么要加这个。 比如你是为了不让B站检测到你的访问来源，从而检测到盗链。

2020-03-08 14:46 UTC, azl397985856 commented on .eslintrc.js
> +    //'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off' ,
不要单独在这里加。 让@大弟子 加就好

2020-03-08 14:46 UTC, azl397985856 commented on src/views/Video.vue
> +      if (iframe) {
不建议使用ref

2020-03-08 14:46 UTC, azl397985856 commented on src/views/Video.vue
> +      pageSize: 2
2太小了。  我猜测你是为了测试分页，但是提交代码要改回来呀。


而且2应该做成常量

2020-03-08 14:46 UTC, azl397985856 commented on src/views/Video.vue
> +    this.getAllUserAllVideo()
```suggestion
    this.getAllUserAllVideo(USERLIST)
```

2020-03-08 14:46 UTC, azl397985856 commented on src/views/Video.vue
> +    getAllUserAllVideo() {
```suggestion
    getAllUserAllVideo(USERLIST) {

```

2020-03-08 14:46 UTC, azl397985856 commented on src/views/Video.vue
> +        this.getUserAllVideo(item)
```suggestion
        this.getUserAllVideo

```

2020-03-08 14:46 UTC, azl397985856 commented on src/views/Video.vue
> +      USERLIST.map(item => {
```suggestion
      USERLIST.map(item => 

```

2020-03-08 14:46 UTC, azl397985856 commented on src/views/Video.vue
> +      })
```suggestion
      )

```

2020-03-08 14:46 UTC, azl397985856 commented on src/views/Video.vue
> +    getUserAllVideo(mid) {
增加loading

2020-03-08 14:46 UTC, azl397985856 commented on src/views/Video.vue
> +      this.videoSrc = `//player.bilibili.com/player.html?aid=${aid}`
增加loading

2020-03-08 14:46 UTC, azl397985856 commented on src/views/Video.vue
> +          const data = res.data.data
方法太复杂。 建议切分为多个函数，并通过函数名字告知函数的意图

2020-03-09 07:01 UTC, azl397985856 requested changes

2020-03-09 07:01 UTC, azl397985856 commented on src/views/Video.vue
> +      tagList.unshift({
改用无副作用的函数。 比如concat slice等

2020-03-09 07:01 UTC, azl397985856 commented on src/views/Video.vue
> +          mid
这里功能还是可以进一步拆分为多个函数

2020-03-15 07:30 UTC, ZStar01 commented on src/views/Video.vue
> +      this.videoSrc = `//player.bilibili.com/player.html?aid=${aid}`
已新增

2020-03-16 04:08 UTC, azl397985856 approved these changes

2020-03-16 05:07 UTC, 474382587 approved these changes

2020-03-16 05:12 UTC, merged