题解页面完成
yulecc/lucifer-official-web pull request #66
Opened 2020-04-10 11:17 UTC by ZStar01

2020-04-11 08:22 UTC, azl397985856 requested changes
没有单元测试

常量命名方式不对(P1)

没有readme

2020-04-11 08:23 UTC, azl397985856 reviewed
console 不删除，生产打包会挂吧？(p1)

2020-04-12 06:19 UTC, azl397985856 approved these changes

2020-04-12 06:36 UTC, yulecc requested changes

2020-04-12 06:36 UTC, yulecc commented on src/views/Solution.vue
> +      <template slot="Title" slot-scope="text, record">
slot-scope在vue3.0中会被废弃，建议使用v-slot

2020-04-12 06:36 UTC, yulecc commented on src/views/Solution.vue
> +    handleClick(record, index) {
index没有用到，建议删除

2020-04-12 06:36 UTC, yulecc commented on src/views/SolutionDetail.vue
> +<style lang="less" scoped>
虽然用的less，但是写法里并没有用到啊

2020-04-12 07:01 UTC, ZStar01 commented on src/views/Solution.vue
> +      <template slot="Title" slot-scope="text, record">
这个是antd的用法

2020-04-12 07:01 UTC, ZStar01 commented on src/views/Solution.vue
> +    handleClick(record, index) {
已删

2020-04-12 07:03 UTC, ZStar01 commented on src/views/SolutionDetail.vue
> +<style lang="less" scoped>
这个界面比较简单,就这几个简单的class,不懂你说的没用到是什么意思

2020-04-12 07:17 UTC, yulecc approved these changes

2020-04-12 12:34 UTC, merged