Fix/zstar01 video
yulecc/lucifer-official-web pull request #77
Opened 2020-04-16 10:15 UTC by ZStar01

**fix:**
video page serveless requst address
mobile style

2020-04-16 10:24 UTC, azl397985856 requested changes

2020-04-16 10:24 UTC, azl397985856 commented on src/views/Video.vue
> +  #wrapper {
why ID？ Not class？

2020-04-16 11:51 UTC, ZStar01 commented on src/views/Video.vue
> +  #wrapper {
已修改

2020-04-17 02:18 UTC, azl397985856 approved these changes

2020-04-17 03:02 UTC, yulecc approved these changes

2020-04-17 03:13 UTC, merged